version: '3.8'

services:
  orderdb:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong(!)Password"
    restart: always
    ports:
      - "1433:1433"
  
  basketdb:
    restart: always
    ports:
      - "6379:6379"
  
  rabbitmq:
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  ordering.webapi:
    image: ${DOCKER_REGISTRY-}orderingwebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderingDb;User Id=sa;Password=YourStrong(!)Password"
      - "EventBusSettings:Host=rabbitmq:5672"
      - "EventBusSettings:UserName=guest"
      - "EventBusSettings:Password=guest"
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8004:80"
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RedisSettings:ConnectionString=basketdb:6379"
      - "EventBusSettings:Host=rabbitmq:5672"
      - "EventBusSettings:UserName=guest"
      - "EventBusSettings:Password=guest"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:80"
