version: '3.8'

services:
  orderdb:
    container_name: orderdb
    image: mcr.microsoft.com/mssql/server:2019-latest
  basketdb:
    image: redis:alpine
    container_name: basketdb
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
  
  ordering.webapi:
    container_name: ordering.webapi
    build:
      context: .
      dockerfile: Ordering/Ordering.WebApi/Dockerfile
    
  basket.api:
    container_name: basket.api
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile
      
  shopping.aggregator:
    container_name: shopping.aggregator
    build:
      context: .
      dockerfile: ApiGateways/Shopping/Dockerfile
      

  