version: '3.8'

services:
  orderdb:
    container_name: orderdb
  basketdb:
    container_name: basketdb
  
  ordering.webapi:
    container_name: ordering.webapi
    build:
      context: .
      dockerfile: Ordering/Ordering.WebApi/Dockerfile
    
  basket.api:
    container_name: basket.api
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile

  