version: '3.8'

services:
  orderdb:
    container_name: orderdb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong(!)Password"
    restart: always
    ports:
      - "1433:1433"